# Generated by Django 4.2.3 on 2023-07-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('essencial', models.BooleanField(default=False)),
                ('valor_planejamento', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=50)),
                ('banco', models.CharField(choices=[('NU', 'Nubank'), ('CX', 'Caixa Economica'), ('BB', 'Banco do Brasil'), ('BR', 'Bradesco'), ('IT', 'Itau'), ('SC', 'Sicred cooperativa'), ('SI', 'Sicoob'), ('SA', 'Satander')], max_length=2)),
                ('tipo', models.CharField(choices=[('pf', 'pessoa fisica'), ('pj', 'pessoa juridica')], max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('icone', models.ImageField(upload_to='icones')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
    ]
